version: 2
jobs:
  build:
    working_directory: ~/Cardcraft.API
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build