version: 2
jobs:
  build:
    working_directory: ~/Cardcraft.API
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${CARDCRAFT_ACCOUNT_FINGERPRINT}"
            - "${CARDCRAFT_PRODUCT_FINGERPRINT}"
            - "${CARDCRAFT_PAYMENT_FINGERPRINT}"
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: find .
      - run: dotnet restore
      - run: dotnet build